<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="4" total="7" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Regression Suite" duration-ms="31663" started-at="2020-01-25T13:00:27 EST" finished-at="2020-01-25T13:00:58 EST">
    <groups>
      <group name="regression">
        <method signature="AddEmployeePageTest.addMultipleEmpoyee(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.hrms.testcases.AddEmployeePageTest@167fdd33]" name="addMultipleEmpoyee" class="com.hrms.testcases.AddEmployeePageTest"/>
        <method signature="LeaveListPageTest.leaveLabelvalidation()[pri:0, instance:com.hrms.testcases.LeaveListPageTest@6acdbdf5]" name="leaveLabelvalidation" class="com.hrms.testcases.LeaveListPageTest"/>
        <method signature="LeaveListPageTest.leaveLabelvalidation1()[pri:0, instance:com.hrms.testcases.LeaveListPageTest@6acdbdf5]" name="leaveLabelvalidation1" class="com.hrms.testcases.LeaveListPageTest"/>
      </group> <!-- regression -->
    </groups>
    <test name="Regression Test" duration-ms="31663" started-at="2020-01-25T13:00:27 EST" finished-at="2020-01-25T13:00:58 EST">
      <class name="com.hrms.testcases.AddEmployeePageTest">
        <test-method status="PASS" signature="generateReports()[pri:0, instance:com.hrms.testcases.AddEmployeePageTest@167fdd33]" name="generateReports" is-config="true" duration-ms="103" started-at="2020-01-25T13:00:27 EST" finished-at="2020-01-25T13:00:27 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReports -->
        <test-method status="SKIP" signature="addMultipleEmpoyee(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.hrms.testcases.AddEmployeePageTest@167fdd33]" name="addMultipleEmpoyee" duration-ms="0" started-at="2020-01-25T13:00:27 EST" data-provider="getData" finished-at="2020-01-25T13:00:27 EST">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:50)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:146)
at org.testng.internal.Parameters.handleParameters(Parameters.java:820)
at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at com.hrms.utils.ExcelUtility.rowCount(ExcelUtility.java:41)
at com.hrms.utils.ExcelUtility.excelIntoArray(ExcelUtility.java:75)
at com.hrms.testcases.AddEmployeePageTest.getData(AddEmployeePageTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:77)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:46)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addMultipleEmpoyee -->
        <test-method status="PASS" signature="writeReport()[pri:0, instance:com.hrms.testcases.AddEmployeePageTest@167fdd33]" name="writeReport" is-config="true" duration-ms="264" started-at="2020-01-25T13:00:58 EST" finished-at="2020-01-25T13:00:58 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeReport -->
      </class> <!-- com.hrms.testcases.AddEmployeePageTest -->
      <class name="com.hrms.testcases.LeaveListPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.hrms.testcases.LeaveListPageTest@6acdbdf5]" name="setUp" is-config="true" duration-ms="5716" started-at="2020-01-25T13:00:27 EST" finished-at="2020-01-25T13:00:33 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="leaveLabelvalidation()[pri:0, instance:com.hrms.testcases.LeaveListPageTest@6acdbdf5]" name="leaveLabelvalidation" duration-ms="8459" started-at="2020-01-25T13:00:33 EST" finished-at="2020-01-25T13:00:42 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- leaveLabelvalidation -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hrms.testcases.LeaveListPageTest@6acdbdf5]" name="tearDown" is-config="true" duration-ms="923" started-at="2020-01-25T13:00:42 EST" finished-at="2020-01-25T13:00:43 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.hrms.testcases.LeaveListPageTest@6acdbdf5]" name="setUp" is-config="true" duration-ms="4974" started-at="2020-01-25T13:00:43 EST" finished-at="2020-01-25T13:00:48 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="leaveLabelvalidation1()[pri:0, instance:com.hrms.testcases.LeaveListPageTest@6acdbdf5]" name="leaveLabelvalidation1" duration-ms="9216" started-at="2020-01-25T13:00:48 EST" finished-at="2020-01-25T13:00:57 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.hrms.testcases.LeaveListPageTest.leaveLabelvalidation1(LeaveListPageTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- leaveLabelvalidation1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hrms.testcases.LeaveListPageTest@6acdbdf5]" name="tearDown" is-config="true" duration-ms="844" started-at="2020-01-25T13:00:57 EST" finished-at="2020-01-25T13:00:58 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hrms.testcases.LeaveListPageTest -->
    </test> <!-- Regression Test -->
  </suite> <!-- Regression Suite -->
</testng-results>
